# Site
repository: bmangoen/cv
favicon: images/favicon.ico

# Personal info
name: Brian M
title: Cloud consultant
email: bmangoen@redhat.com
website: bmangoen.github.io/blog

# Social links
github_username:  bmangoen
linkedin_username: bmangoen
twitter_username: _bmangoen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: brian
# pinterest_username: jekyll
# youtube_username: brian
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brian and I'm a Cloud consultant for Red Hat.
  
  I’m a passionate of automation and I'm always discovering the vast world of cloud computing.

  During my experiences and projects, I had the chance to write several Ansible playbooks to get automatically an application running on the Cloud for example. 
  For orchestrating containerized applications, I have also deployed, operated and used OpenShift in many specific customer environments.

  I’m now interested in working on these projects by contributing and helping other engineers to improve these products.

# Certification Section
projects_title: Certification

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in container platforms and software engineering, I like to do different activities which are:
   - Water sports like surfing, SUP (Stand Up Paddling)
   - Brazilian Jiujitsu
   - Rock climbing
   - Football

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

darkmode: true