# Site
repository: bmangoen/cv
favicon: images/favicon.ico

# Personal info
name: Brian M.
title: Cloud consultant
email: bmangoen@redhat.com
website: bmangoen.github.io/blog

# Social links
github_username:  bmangoen
linkedin_username: bmangoen
twitter_username: _bmangoen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: brian
# pinterest_username: jekyll
# youtube_username: brian
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/gopherizeme.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Brian and I'm a french cloud consultant for Red Hat.
  
  I’m an advocate of automation and a passionate of the containers world.
  Go check below what I did with Ansible and OpenShift ☺

  I’m now interested in working closer on these projects by contributing and helping other engineers to improve these products.

# Certification Section
projects_title: Certification

# Experience Section
experience_title: Professional Experience

# Education Section
# educaton_title: Education

# More Section
more_title: More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in automation, container platforms and software engineering, I like to do different activities which are:
   - Water sports like surfing, SUP (Stand Up Paddling) :
     I love to be in harmony with the ocean and use it to ride.
   - Brazilian Jiujitsu : 
     I really like this martial art because it's very technical and tactical sport. 
     I also improved my humility practising BJJ.
   - Rock climbing :
     I like rock climbing because I have to work on my patience and to surpass myself to progress.
   - Football :
     Thanks to my dad, I'm a Paris Saint Germain fan. 
     I enjoy playing football to be part of a team which has the goal.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

darkmode: true